server:
 port: 8443
 context-path: /mock
 ssl: 
  enabled: true
  key-store: src/main/resources/tomcat.key
  key-store-type: JKS
  kay-alias: tomcat
  key-store-password: 123456
# max-http-header-size: 819200
spring:
  redis:
    host: 192.168.1.121
    port: 6379
    timeout: 20000
  datasource:
    url: jdbc:mysql://192.168.1.121:3306/mock?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Imobpay123456!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    ROOT: DEBUG
socketServer:
  port: 7071
xmlPath: F:\my_project\java\platform-thirdpartymock\src\main\resources\xml\