server:
 port: 9500
 context-path: /mock
spring:
  datasource:
    url: jdbc:mysql://192.168.1.121:3306/mock?useUnicode=true&characterEncoding=utf-8
    username: root
    password: Imobpay123456!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
socketServer:
  port: 7071
xmlPath: F:\my_project\java\platform-thirdpartymock\src\main\resources\xml\